### ISSUE TITLE
Что еще можно сделать

### ISSUE THREAD

**Issue by roslovets** [rodser92/inzhenerka_project-test-#1]
Отлично! Маркдаун освоил, теперь не забывай в новых репо создавать похожий ридми. Главная цель в том, чтобы спустя полгода ты вернулся к проекту и смог завести его за пару минут по инструкции в ридми. Ну и чтобы другие тоже смогли понять, что у тебя тут происходит.
Не смотря на всю очаровательность улучшенного кота, я не смог им насладиться сразу же, пришлось открывать картинку :(
Для тренировки попробуй вставить котана прямо в ридми!

**Comment by rodser92** [comment]
Добавил котика для @roslovets 
[README.md](https://github.com/rodser92/inzhenerka_project-test-/commit/0817d137e91d89349681d447956c9e707644bf43)

**Comment by roslovets** [comment]
👍
