### ISSUE TITLE
Изменения не доставлены

### ISSUE THREAD

**Issue by roslovets** [rodser92/inzhenerka_project-test-#2]
Они так и остались в ветке dev. А как же main?
![image](https://user-images.githubusercontent.com/21337619/205197225-7a542c43-5ef6-45cb-9ad8-584fd300d28f.png)

**Comment by rodser92** [comment]
### Все поправил
![image](https://user-images.githubusercontent.com/119243707/205905940-14d83199-2614-4125-933e-6bc3b334acd3.png)
